tools:
  - class_name: "recipe.code_agentic.code_agentic.SandboxFusionTestCaseTool"
    config:
      sandbox_fusion_url: "http://10.68.171.9:8080/run_code"
      num_workers: 64
      enable_global_rate_limit: true
      rate_limit: 64
      default_timeout: 120
      default_language: "python"
      max_concurrent: 64
      type: native

    tool_schema:
      type: "function"
      function:
        name: "code_interpreter"
        description: "A tool for executing code."
        parameters:
          type: "object"
          properties:
            code:
              type: "string"
              description: "The code to execute."
          required: ["code"]
